:toc: left


= Flingueur

La plupart des guerriers et des spécialistes du combat passent leurs années à perfectionner les arts classiques de l'épée, du tir à l'arc ou de la tactique du bras de fer. Qu'il s'agisse de duelliste ou d'infanterie, les armes martiales semblent avoir été perfectionnées il y a longtemps, et le véritable défi consiste à les maîtriser.

Cependant, certains esprits ne pouvaient pas s'arrêter à l'innovation de l'arbalète. L'expérimentation de composants alchimiques et de métaux rares a permis de percer les secrets de la force explosive contrôlée. Les quelques personnes qui survivront à ces épreuves d'ingéniosité seront peut-être les premières à créer et à manier habilement les premières armes à feu.

Cet archétype se concentre sur la capacité à concevoir, fabriquer et utiliser des armes à distance puissantes mais dangereuses. Grâce à une innovation créative et à une visée immaculée, vous devenez une force de mort à distance sur le champ de bataille. Cependant, n'étant pas une science parfaite, les armes à feu comportent une instabilité inhérente qui peut parfois vous laisser sans moyen d'attaque fonctionnel. C'est le danger des technologies nouvelles, non testées, dans un monde où les énergies arcaniques qui régissent les éléments sont toujours présentes.

Si cette voie de la poudre, du feu et du métal vous appelle, gardez votre esprit, tenez à vos convictions de combattant, et laissez l'habileté et la chance guider vos balles pour qu'elles frappent juste.


== Compétence en armes à feu

À partir du moment où vous choisissez cet archétype au 3e niveau, vous gagnez la compétence en armes à feu, ce qui vous permet d'ajouter votre bonus de compétence aux attaques effectuées avec des armes à feu.

== Armurier

En choisissant cet archétype au 3e niveau, vous gagnez la compétence avec les outils du bricoleur. Vous pouvez les utiliser pour fabriquer des munitions à moitié prix, réparer des armes à feu endommagées, ou même en dessiner et en créer de nouvelles (à la discrétion du MJ). Certaines armes à feu extrêmement expérimentales et complexes ne sont disponibles que par le biais de l'artisanat.

=== Propriétés des armes à feu

Les armes à feu sont une technologie nouvelle et volatile, et en tant que telle, elles apportent leur propre ensemble de propriétés uniques. Certaines propriétés sont suivies d'un nombre, et ce nombre signifie un élément de cette propriété (décrit ci-dessous). Ces propriétés remplacent les propriétés optionnelles présentées dans le Guide du Maître du Donjon. Les armes à feu sont des armes à distance.

==== Recharge

L'arme peut être utilisée un nombre de fois égal à son score de rechargement avant que vous ne deviez dépenser 1 attaque ou 1 action pour la recharger. Vous devez avoir une main libre pour recharger une arme à feu.

==== Raté de tir

Chaque fois que vous effectuez un jet d'attaque avec une arme à feu et que le résultat du dé est inférieur ou égal au score de raté de l'arme, celle-ci a des ratés. L'attaque est ratée et l'arme ne peut plus être utilisée jusqu'à ce que vous dépensiez une action pour essayer de la réparer. Pour réparer votre arme à feu, vous devez réussir un test d'Outils du bricoleur (DC égal à 8 + score de ratés). Si votre test échoue, l'arme est cassée et doit être réparée hors combat pour un quart du coût de l'arme à feu. Les créatures qui utilisent une arme à feu sans être compétentes augmentent le score de raté de l'arme de 1.

==== Explosif 

En cas de succès, tout ce qui se trouve à 1,5 m de la cible doit effectuer un jet de sauvegarde de Dextérité (DC égal à 8 + votre bonus de compétence + votre modificateur de Dextérité) ou subir 1d8 dégâts de feu. Si l'arme rate son coup, les munitions n'explosent pas ou rebondissent avant de le faire.

=== Munitions

Toutes les armes à feu ont besoin de munitions pour effectuer une attaque, et en raison de leur rareté, les munitions peuvent être presque impossibles à trouver ou à acheter. Cependant, si vous trouvez des matériaux, vous pouvez fabriquer vous-même des munitions à l'aide de vos outils de bricoleur pour la moitié du coût. Chaque arme à feu utilise des munitions qui lui sont propres et est généralement vendue ou fabriquée par lots, indiqués ci-dessous à côté du prix.

==== Armes à feu
Nom Coût Munitions Dommages Poids Portée Propriétés
Pistolet de poche 50g 2g (20) 1d8 perçant 1 lb (40/160) 	
Léger, recharge 1, raté 1
Pistolet 150g 4g (20) 1d10 perçant 3 lb (60/240) 	
Recharge 4, raté 1
Mousquet 300g 5g (20) 1d12 perçant 10 lb (120/480) 	
A deux mains, rechargement 1, raté 2
Poivrière 250g 4g (20) 1d10 perçant 5 lb (80/320) 	
Recharge 6, raté 2
Gyrophare 300g 5g (5) 2d8 perçant 10 lb (15/60) 	
Recharge 1, raté 2
Bad News Crafted 10g (5) 2d12 perçant 25 lb (200/800) 	
A deux mains, recharge 1, raté 3
Mortier à main Fabrication artisanale 10g (1) 2d8 feu 10 lb (30/60) 	
Recharge 1, raté 3, explosif

== Tireur d'élite adroit

Lorsque vous choisissez cet archétype au 3e niveau, vous apprenez à effectuer de puissants tirs de ruse pour mettre hors d'état de nuire ou endommager vos adversaires à l'aide de vos armes à feu.

==== Trick Shots

Vous apprenez deux coups fourrés de votre choix, qui sont détaillés sous "Coups fourrés" ci-dessous. De nombreuses manœuvres améliorent une attaque d'une manière ou d'une autre. Chaque utilisation d'un coup fourré doit être déclarée avant que le jet d'attaque ne soit effectué. Vous ne pouvez utiliser qu'un seul coup de ruse par attaque.

Vous apprenez un coup de ruse supplémentaire de votre choix au 7e, 10e, 15e et 18e niveau. Chaque fois que vous apprenez un nouveau coup de ruse, vous pouvez également remplacer un coup de ruse que vous connaissez par un autre.

==== Grit

Vous gagnez un nombre de points de cran égal à votre modificateur de sagesse (minimum de 1). Vous regagnez 1 point de cran dépensé chaque fois que vous obtenez un 20 sur le jet de d20 pour une attaque avec une arme à feu, ou que vous portez un coup fatal avec une arme à feu à une créature présentant une menace importante (à la discrétion du MJ). Vous regagnez tous les points de courage dépensés après un repos court ou long.

==== Jets de sauvegarde

Certains de vos coups fourrés nécessitent que vos cibles fassent un jet de sauvegarde pour résister aux effets du coup fourré. Le DC du jet de sauvegarde est calculé comme suit :

   Valeur de sauvegarde du tir de ruse = 8 + votre bonus de compétence + votre modificateur de Dextérité.

== Tirage rapide

Lorsque vous atteignez le 7e niveau, vous ajoutez votre bonus de compétence à votre initiative. Vous pouvez également ranger une arme à feu, puis en tirer une autre comme une seule interaction d'objet à votre tour.

== Réparation rapide

Lorsque vous atteignez le 10e niveau, vous apprenez à tenter de réparer rapidement une arme à feu enrayée. Vous pouvez dépenser un point d'esprit pour tenter de réparer une arme à feu qui a mal fonctionné (mais pas cassée) en tant qu'action bonus.

== Rechargement éclair

À partir du 15e niveau, vous pouvez recharger n'importe quelle arme à feu en tant qu'action bonus.

== Intention vicieuse

Au 18e niveau, vos attaques à l'arme à feu obtiennent un coup critique sur un jet de 19-20, et vous regagnez un point d'esprit sur un jet de 19 ou 20 sur un jet d'attaque d20.

== Hémorragie critique

Lorsque vous atteignez le 18e niveau, chaque fois que vous obtenez un coup critique sur une attaque avec une arme à feu, la cible subit en plus la moitié des dégâts de l'attaque à la fin de son prochain tour.

== Coups fourrés

Ces coups fourrés sont présentés par ordre alphabétique.

=== Tir d'intimidation

Vous pouvez utiliser le souffle puissant et le son tonitruant de votre arme à feu pour ébranler la détermination d'une créature. Vous pouvez dépenser un point d'esprit lorsque vous effectuez un test de Charisme (Intimidation) pour obtenir un avantage sur le jet.

=== Tir étourdissant

Lorsque vous effectuez une attaque avec une arme à feu contre une créature, vous pouvez dépenser un point de courage pour tenter d'étourdir votre adversaire. En cas de succès, la créature subit des dégâts normaux et doit effectuer un jet de sauvegarde de Constitution ou subir un désavantage sur les attaques jusqu'à la fin de son prochain tour.

=== Tir à l'aveugle

Lorsque vous effectuez une attaque à l'aide d'une arme à feu contre une créature, vous pouvez dépenser un point de courage pour obtenir un avantage sur le jet d'attaque.

=== Tir de désarmement

Lorsque vous effectuez une attaque par arme à feu contre une créature, vous pouvez dépenser un point de difficulté pour tenter de lui tirer un objet des mains. Si elle est touchée, la créature subit des dégâts normaux et doit réussir un jet de sauvegarde de Force ou laisser tomber un objet tenu de votre choix et le voir être poussé à 10 pieds de vous.

=== Tir puissant

Lorsque vous effectuez une attaque par arme à feu contre une créature, vous pouvez dépenser un point de grit pour tenter de la faire trébucher et de la forcer à reculer. En cas de succès, la créature subit des dégâts normaux et doit réussir un jet de sauvegarde de Force ou être repoussée à 15 pieds de vous.

=== Tir perçant

Lorsque vous effectuez une attaque d'arme à feu contre une créature, vous pouvez dépenser un point de courage pour tenter de tirer à travers plusieurs adversaires. L'attaque initiale bénéficie d'un +1 au score de raté de l'arme à feu. En cas de succès, la créature subit des dégâts normaux et vous effectuez un jet d'attaque avec désavantage contre chaque créature en ligne directement derrière la cible dans votre premier incrément de portée. Seule l'attaque initiale peut avoir des ratés.

=== Tir violent

Lorsque vous effectuez une attaque à l'aide d'une arme à feu contre une créature, vous pouvez dépenser un ou plusieurs points de courage pour augmenter la volatilité de l'attaque. Pour chaque point de cran dépensé, l'attaque gagne un +2 au score de raté de l'arme à feu. Si l'attaque touche, vous pouvez lancer un dé de dégâts d'arme supplémentaire par point de cran dépensé pour déterminer les dégâts.

=== Tir à l'aile

Lorsque vous effectuez une attaque avec une arme à feu contre une créature, vous pouvez dépenser un point de difficulté pour tenter de renverser une cible en mouvement. En cas de succès, la créature subit des dégâts normaux et doit effectuer un jet de sauvegarde de Force ou être mise à terre.
